import Link from "next/link";
import style from "./layout.module.css";
import zLogo from "@/../public/zlogo.png";
import Image from "next/image";
import { Metadata } from "next";

const user = {
  name: "와우와우",
  username: "richdad",
  avatarUrl: "/cat.jpg",
};

export const metadata: Metadata = {
  title: "홈 / Z",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className={style.main}>
      <div className={style.leftSection}>
        <div className={style.logo}>
          <Link href="/home">
            <Image src={zLogo} alt="z.com logo" width={40} />
          </Link>
        </div>
        <div className={style.menu}>
          <nav>
            <ul>
              <Link href="/home">
                <li className={style.menuItem}>
                  <svg width="26" viewBox="0 0 24 24" aria-hidden="true">
                    <g>
                      <path d="M12 1.696L.622 8.807l1.06 1.696L3 9.679V19.5C3 20.881 4.119 22 5.5 22h13c1.381 0 2.5-1.119 2.5-2.5V9.679l1.318.824 1.06-1.696L12 1.696zM12 16.5c-1.933 0-3.5-1.567-3.5-3.5s1.567-3.5 3.5-3.5 3.5 1.567 3.5 3.5-1.567 3.5-3.5 3.5z"></path>
                    </g>
                  </svg>
                  <span className={style.menuText}>홈</span>
                </li>
              </Link>
              <Link href="/explore">
                <li className={style.menuItem}>
                  <svg width="26" viewBox="0 0 24 24" aria-hidden="true">
                    <g>
                      <path d="M10.25 3.75c-3.59 0-6.5 2.91-6.5 6.5s2.91 6.5 6.5 6.5c1.795 0 3.419-.726 4.596-1.904 1.178-1.177 1.904-2.801 1.904-4.596 0-3.59-2.91-6.5-6.5-6.5zm-8.5 6.5c0-4.694 3.806-8.5 8.5-8.5s8.5 3.806 8.5 8.5c0 1.986-.682 3.815-1.824 5.262l4.781 4.781-1.414 1.414-4.781-4.781c-1.447 1.142-3.276 1.824-5.262 1.824-4.694 0-8.5-3.806-8.5-8.5z"></path>
                    </g>
                  </svg>
                  <span className={style.menuText}>탐색하기</span>
                </li>
              </Link>
              <Link href="/messages">
                <li className={style.menuItem}>
                  <svg width="26" viewBox="0 0 24 24" aria-hidden="true">
                    <g>
                      <path d="M1.998 5.5c0-1.381 1.119-2.5 2.5-2.5h15c1.381 0 2.5 1.119 2.5 2.5v13c0 1.381-1.119 2.5-2.5 2.5h-15c-1.381 0-2.5-1.119-2.5-2.5v-13zm2.5-.5c-.276 0-.5.224-.5.5v2.764l8 3.638 8-3.636V5.5c0-.276-.224-.5-.5-.5h-15zm15.5 5.463l-8 3.636-8-3.638V18.5c0 .276.224.5.5.5h15c.276 0 .5-.224.5-.5v-8.037z"></path>
                    </g>
                  </svg>
                  <span className={style.menuText}>쪽지</span>
                </li>
              </Link>
              <Link href="/richdad">
                <li className={style.menuItem}>
                  <svg width="26" viewBox="0 0 24 24" aria-hidden="true">
                    <g>
                      <path d="M5.651 19h12.698c-.337-1.8-1.023-3.21-1.945-4.19C15.318 13.65 13.838 13 12 13s-3.317.65-4.404 1.81c-.922.98-1.608 2.39-1.945 4.19zm.486-5.56C7.627 11.85 9.648 11 12 11s4.373.85 5.863 2.44c1.477 1.58 2.366 3.8 2.632 6.46l.11 1.1H3.395l.11-1.1c.266-2.66 1.155-4.88 2.632-6.46zM12 4c-1.105 0-2 .9-2 2s.895 2 2 2 2-.9 2-2-.895-2-2-2zM8 6c0-2.21 1.791-4 4-4s4 1.79 4 4-1.791 4-4 4-4-1.79-4-4z"></path>
                    </g>
                  </svg>
                  <span className={style.menuText}>프로필</span>
                </li>
              </Link>
            </ul>
          </nav>
          <Link href="/compose/tweet">
            <button className={style.actionButton}>게시하기</button>
          </Link>
        </div>
        <div className={style.logoutDiv}>
          <Link className={style.logout} href="/logout">
            <span className={style.logoutPhoto}>
              <img src={user.avatarUrl} alt="user profile image" />
            </span>
            <div className={style.logoutTextDiv}>
              <p className={style.logoutTitle}>{user.name}</p>
              <p className={style.logoutBody}>@{user.username}</p>
            </div>
          </Link>
        </div>
      </div>

      <div>{children}</div>
      <div className={style.rightSection}></div>
    </div>
  );
}
