import style from "./layout.module.css";
import { Metadata } from "next";
import SearchBar from "./home/_component/SearchBar";
import FollowRecommend from "./_componenet/FollowRecommend";
import NavList from "./_componenet/NavList";
import RightSection from "./_componenet/RightSection";

type Props = {
  children: React.ReactNode;
  modal: React.ReactNode;
};

export const metadata: Metadata = {
  title: "홈 / Z",
  description: "Generated by create next app",
};

export default function Layout({ children, modal }: Props) {
  return (
    <div className={style.main}>
      <section className={style.leftSection}>
        <NavList />
      </section>

      <section className={style.centerSection}>{children}</section>
      <section className={style.rightSection}>
        <RightSection />
      </section>
      {modal}
    </div>
  );
}
